[global]
color = "#FFFFFF"
focused_color = "#FFFFFF"
icon = "类"
size = "14pt"

[app_id]
"dev.alextren.Spot" = { icon = "阮", color = "#1ed760" }
"org.gnome.Nautilus" = { icon = "", color = "#6291d6" }
1Password = { icon = "", color = "#0572ec" }
Alacritty = { icon = "" }
Deezer = { icon = "", color = "#ef5466" }
Slack = { icon = "聆", color = "#2eb67d" }
Spotify = { icon = "阮", color = "#1ed760" }
beekeeper-studio = { icon = "", color = "#fad83b" }
chromium = { icon = "", color = "#a1c2fa", size = "13pt" }
firefox = { icon = "", color = "#ff8817", size = "13pt" }
foot = { icon = "" }
geary = { icon = "", color = "#f6d32d" }
gnome-calendar = { icon = "", color = "#3584e4" }
google-chrome = { icon = "", color = "#4285f4" }
neovide = { icon = "", color = "#8fff6d" }
nvim-qt = { icon = "", color = "#8fff6d" }
shotwell = { icon = "", color = "#4f7aaf" }
zoom = { icon = "", color = "#2d8cff" }

[title]
"(cloud|developers)\\.google.com" = { icon = "", color = "#4285f4" }
"192\\.168\\.0\\.1|192\\.168\\.86\\.1|ui\\.com" = { icon = "直", color = "#004cb6" }
"1password\\.com" = { icon = "", color = "#0572ec" }
"amazon\\.com" = { icon = "", color = "#ff9900" }
"angular\\.io" = { icon = "", color = "#dd0031" }
"archlinux\\.org" = { icon = "", color = "#1793d1" }
"atlassian\\.(net|com)" = { icon = "", color = "#0052cc" }
"aws\\.amazon\\.com" = { icon = "", color = "#ff9900" }
"bitbucket\\.org" = { icon = "", color = "#0052cc" }
"calendar\\.google\\.com" = { icon = "", color = "#4285f4" }
"crates\\.io" = { icon = "", color = "#ffc933" }
"deezer\\.com" = { icon = "", color = "#ef5466" }
"docs\\.google\\.com" = { icon = "", color = "#4285f4" }
"docs\\.rs|rust-lang\\.org" = { icon = "", size = "16pt" }
"drive\\.google\\.com" = { icon = "", color = "#4285f4" }
"dropbox\\.com" = { icon = "", color = "#0061fe" }
"duckduckgo\\.com" = { icon = "", color = "#de5833" }
"facebook\\.com" = { icon = "", color = "#1877f2" }
"fastmail\\.com" = { icon = "﫯", color = "#1565c0" }
"feedbin\\.com" = { icon = "" }
"gitbook\\.com" = { icon = "", color = "#346ddb" }
"github\\.com" = { icon = "" }
"google\\.com" = { icon = "", color = "#4285f4" }
"google\\.com/maps" = { icon = "﫴", color = "#4caf50" }
"keep\\.google\\.com" = { icon = "ﯚ", color = "#fbbc04" }
"last\\.fm" = { icon = "", color = "#ba0000" }
"mail\\.google\\.com" = { icon = "", color = "#ad1f1c" }
"meet\\.google\\.com" = { icon = "", color = "#4285f4" }
"messages\\.google\\.com" = { icon = "", color = "#4285f4" }
"mozilla\\.org" = { icon = "" }
"nerdfonts\\.com" = { icon = "", color = "#ffce3e" }
"photos\\.google\\.com" = { icon = "", color = "#4285f4" }
"reactjs\\.org" = { icon = "", color = "#61dafb" }
"reddit\\.com" = { icon = "樓", color = "#ff4500" }
"slack\\.com" = { icon = "聆", color = "#2eb67d" }
"spotify\\.com" = { icon = "阮", color = "#1ed760" }
"sr\\.ht|sourcehut\\.org" = { icon = "" }
"stackoverflow\\.com" = { icon = "", color = "#f48225" }
"startpage\\.com" = { icon = "", color = "#6573ff" }
"stripe\\.com" = { icon = "", color = "#635bff" }
"todoist\\.com" = { icon = "", color = "#e44232" }
"travis-ci\\.(com|org)" = { icon = "", color = "#cd324a" }
"twitter\\.com" = { icon = "", color = "#1d9bf0" }
"zoom\\.us" = { icon = "", color = "#2d8cff" }
nnn = { app_id = ["foot", "Alacritty"], icon = "" }
vim = { app_id = ["foot", "Alacritty"], icon = "", color = "#8fff6d" }
pgcli = { app_id = ["foot", "Alacritty"], icon = "", color = "#c74451" }
litecli = { app_id = ["foot", "Alacritty"], icon = "", color = "#c74451" }
aerc = { app_id = ["foot", "Alacritty"], icon = "" }
